services:
    postgresql:
        container_name: ms_pg_sql
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
        volumes:
            - postgres:/data/postgres
        ports:
            - "5433:5432"
        networks:
            - microservices-net
        restart: unless-stopped
    postgresql_account:
        container_name: ms_pg_sql_account
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
            POSTGRES_DB: account
        volumes:
            - postgres_account:/data/postgres
        ports:
            - "5434:5432"
        networks:
            - microservices-net
        restart: unless-stopped
    postgresql_inventory:
        container_name: ms_pg_sql_inventory
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
            POSTGRES_DB: inventory
        volumes:
            - postgres_inventory:/data/postgres
        ports:
            - "5440:5432"
        networks:
            - microservices-net
    postgresql_payment:
        container_name: ms_pg_sql_payment
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
            POSTGRES_DB: payment
        volumes:
            - postgres_payment:/data/postgres
        ports:
            - "5435:5432"
        networks:
            - microservices-net
        restart: unless-stopped
    pgadmin:
        container_name: ms_pgadmin
        image: dpage/pgadmin4:9
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            TZ: UTC
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - microservices-net
        restart: unless-stopped

    zipkin:
        container_name: ms_zipkin
        image: openzipkin/zipkin:3
        environment:
            - TZ=UTC
        ports:
            - "9411:9411"
        networks:
            - microservices-net
    prometheus:
        image: prom/prometheus:latest
        container_name: ms_prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
    grafana:
        image: grafana/grafana:latest
        container_name: ms_grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
    mongodb:
        container_name: ms_mongo_db
        image: mongo:8
        ports:
            - 27017:27017
        volumes:
            - mongo:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
    mongodb_payment:
        container_name: ms_mongodb_payment
        image: mongo:8
        ports:
            - 27023:27017
        volumes:
            - mongo_payment:/data
        networks:
            - microservices-net
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
    mongodb_rating:
        container_name: ms_mongo_db_rating
        image: mongo:8
        ports:
            - 27018:27017
        volumes:
            - mongo_rating:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_auth:
        container_name: ms_mongo_db_auth
        image: mongo:8 
        ports:
            - 27020:27017
        volumes:
            - mongo_auth:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_account:
        container_name: ms_mongo_db_account
        image: mongo:8 
        ports:
            - 27021:27017
        volumes:
            - mongo_account:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_inventory:
        container_name: ms_mongo_db_inventory
        image: mongo:8
        ports:
            - 27022:27017
        volumes:
            - mongo_inventory:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_order:
        container_name: ms_mongo_db_order
        image: mongo:8
        ports:
            - 27019:27017
        volumes:
            - mongo_order:/data
            - ./mongodb.key:/data/configdb/mongodb.key
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        command: mongod --replSet rs0 
             --keyFile /data/configdb/mongodb.key 
             --bind_ip_all
        entrypoint: [ "/bin/sh", "-c", "chown 999:999 /data/configdb/mongodb.key && chmod 400 /data/configdb/mongodb.key && exec docker-entrypoint.sh $$@" ]
        networks:
            - microservices-net
    mongo-express:
        container_name: ms_mongo_express
        image: mongo-express:1
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=alibou
            - ME_CONFIG_MONGODB_ADMINPASSWORD=alibou
            - ME_CONFIG_MONGODB_SERVER=mongodb

    zookeeper:
        container_name: ms_zookeeper
        image: confluentinc/cp-zookeeper:7.7.7
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "22181:2181"
        networks:
            - microservices-net

    kafka:
        container_name: ms_kafka
        image: confluentinc/cp-kafka:7.7.7
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            TZ: UTC
        networks:
            - microservices-net

    mail-dev:
        container_name: ms_mail_dev
        image: maildev/maildev:latest
        ports:
            - 1080:1080
            - 1025:1025

    keycloak:
        container_name: ms_keycloak
        image: quay.io/keycloak/keycloak:26.5
        ports:
            - 9098:8080
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        networks:
            - microservices-net
        command:
            - "start-dev"
    redis:
        image: redis:7.2-alpine  
        container_name: redis_cart
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning --requirepass binh123 --appendonly yes
        volumes:
            - redis_data:/data
        networks:
            - microservices-net

networks:
    microservices-net:
        driver: bridge

volumes:
    postgres:
    postgres_account:
    pgadmin:
    mongo:
    mongo_rating:
    postgres_payment:
    mongo_order:
    redis_data:
    postgres_inventory:
    mongo_auth:
    mongo_account:
    mongo_inventory:
    mongo_payment:
