services:
    postgresql:
        container_name: ms_pg_sql
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
        volumes:
            - postgres:/data/postgres
        ports:
            - "5433:5432"
        networks:
            - microservices-net
        restart: unless-stopped
    postgresql_account:
        container_name: ms_pg_sql_account
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
            POSTGRES_DB: account
        volumes:
            - postgres_account:/data/postgres
        ports:
            - "5434:5432"
        networks:
            - microservices-net
        restart: unless-stopped
    postgresql_inventory:
        container_name: ms_pg_sql_inventory
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
            POSTGRES_DB: inventory
        volumes:
            - postgres_inventory:/data/postgres
        ports:
            - "5440:5432"
        networks:
            - microservices-net
    postgresql_payment:
        container_name: ms_pg_sql_payment
        image: postgres:18
        environment:
            POSTGRES_USER: alibou
            POSTGRES_PASSWORD: alibou
            PGDATA: /data/postgres
            TZ: UTC
            POSTGRES_DB: payment
        volumes:
            - postgres_payment:/data/postgres
        ports:
            - "5435:5432"
        networks:
            - microservices-net
        restart: unless-stopped
    pgadmin:
        container_name: ms_pgadmin
        image: dpage/pgadmin4:9
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            TZ: UTC
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - microservices-net
        restart: unless-stopped

    zipkin:
        container_name: ms_zipkin
        image: openzipkin/zipkin:3
        environment:
            - TZ=UTC
        ports:
            - "9411:9411"
        networks:
            - microservices-net
    prometheus:
        image: prom/prometheus:latest
        container_name: ms_prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
    grafana:
        image: grafana/grafana:latest
        container_name: ms_grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - prometheus
    tempo:
        image: grafana/tempo:latest
        container_name: ms_tempo
        command: [ "-config.file=/etc/tempo.yml" ]
        volumes:
            - ./tempo-config.yml:/etc/tempo.yml
        ports:
            - "4317:4317"  # OTLP gRPC
            - "4318:4318"  # OTLP HTTP (Spring Boot 3 thường dùng cái này)
            - "3200:3200"  # Tempo UI/API
    mongodb:
        container_name: ms_mongo_db
        build:
            context: ./mongo
            dockerfile: Dockerfile
        image: mongo:8-rs
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
    mongodb_payment:
        container_name: ms_mongodb_payment
        image: mongo:8
        ports:
            - 27023:27017
        volumes:
            - mongo_payment:/data
        networks:
            - microservices-net
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
    mongodb_rating:
        container_name: ms_mongo_db_rating
        image: mongo:8
        ports:
            - 27018:27017
        volumes:
            - mongo_rating:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_auth:
        container_name: ms_mongo_db_auth
        image: mongo:8 
        ports:
            - 27020:27017
        volumes:
            - mongo_auth:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_account:
        container_name: ms_mongo_db_account
        image: mongo:8 
        ports:
            - 27021:27017
        volumes:
            - mongo_account:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_inventory:
        container_name: ms_mongo_db_inventory
        image: mongo:8
        ports:
            - 27022:27017
        volumes:
            - mongo_inventory:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongodb_order:
        container_name: ms_mongo_db_order
        image: mongo:8
        ports:
            - 27019:27017
        volumes:
            - mongo_order:/data
            - ./mongodb.key:/data/configdb/mongodb.key
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        command: mongod --replSet rs0 
             --keyFile /data/configdb/mongodb.key 
             --bind_ip_all
        entrypoint: [ "/bin/sh", "-c", "chown 999:999 /data/configdb/mongodb.key && chmod 400 /data/configdb/mongodb.key && exec docker-entrypoint.sh $$@" ]
        networks:
            - microservices-net
    mongodb_notification:
        container_name: ms_mongdb_notification
        image: mongo:8
        ports:
           - 20720:27017
        volumes:
           - mongo_notification:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=alibou
            - MONGO_INITDB_ROOT_PASSWORD=alibou
            - TZ=UTC
        networks:
            - microservices-net
    mongo-express:
        container_name: ms_mongo_express
        image: mongo-express:1
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=alibou
            - ME_CONFIG_MONGODB_ADMINPASSWORD=alibou
            - ME_CONFIG_MONGODB_SERVER=mongo
        networks:
            - microservices-net

    # zookeeper:
    #     container_name: ms_zookeeper
    #     image: confluentinc/cp-zookeeper:8.1.2
    #     environment:
    #         ZOOKEEPER_SERVER_ID: 1
    #         ZOOKEEPER_CLIENT_PORT: 2181
    #         ZOOKEEPER_TICK_TIME: 2000
    #     ports:
    #         - "22181:2181"
    #     networks:
    #         - microservices-net

    kafka:
        container_name: ms_kafka
        image: confluentinc/cp-kafka:8.1.2
        ports:
            - "9092:9092"
        environment:
            # --- KRaft Specific Settings ---
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            # Cluster ID is required for KRaft (You can change this later)
            CLUSTER_ID: 'MAL1fjh8RCCL1yaIwenKDA'

            # --- Listeners Configuration ---
            KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://ms_kafka:29092,PLAINTEXT_HOST://localhost:9092'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'

            # --- Other Settings ---
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            TZ: UTC
        networks:
            - microservices-net

    mail-dev:
        container_name: ms_mail_dev
        image: maildev/maildev:latest
        ports:
            - 1080:1080
            - 1025:1025
        networks:
            - microservices-net

    keycloak:
        container_name: ms_keycloak
        image: quay.io/keycloak/keycloak:26.5
        ports:
            - 9098:8080
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        networks:
            - microservices-net
        command:
            - "start-dev"
    redis_order:
        image: redis:7.2-alpine
        container_name: redis_order
        restart: always
        ports:
            - "6380:6379"
        command: redis-server --save 300 10 --requirepass binh123 --appendonly yes --appendfsync everysec --loglevel warning
        volumes:
            - redis_order:/data
        networks:
            - microservices-net
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "binh123", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
    redis_inventory:
        image: redis:7.2-alpine
        container_name: redis_inventory
        restart: always
        ports:
            - "6381:6379"
        command: redis-server --save 300 10 --requirepass binh123 --appendonly yes --appendfsync everysec --loglevel warning
        volumes:
            - redis_inventory:/data
        networks:
            - microservices-net
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "binh123", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
    redis:
        image: redis:7.2-alpine
        container_name: redis_cart
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 300 10 --requirepass binh123 --appendonly yes --appendfsync everysec --loglevel warning
        volumes:
            - redis_data:/data
        networks:
            - microservices-net
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "binh123", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    microservices-net:
        driver: bridge

volumes:
    postgres:
    postgres_account:
    pgadmin:
    mongo:
    mongo_rating:
    postgres_payment:
    mongo_order:
    redis_data:
    postgres_inventory:
    mongo_auth:
    mongo_account:
    mongo_inventory:
    mongo_payment:
    mongo_notification:
    redis_order:
    redis_inventory:
