spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/account
        username: alibou
        password: alibou
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update 
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8071