spring:
  data:
    redis:
      host: localhost       
      port: 6379
      password: binh123
      timeout: 60000        
      lettuce:
        pool:
          max-active: 8
    mongodb:
      uri: mongodb://alibou:alibou@localhost:27019/order_db?authSource=admin&uuidRepresentation=STANDARD&maxPoolSize=200&minPoolSize=20
      command-listener:
        observation:
          enabled: true
  kafka:
        bootstrap-servers: localhost:9092 
        consumer:
            group-id: order-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
                spring.json.type.mapping: 
                    OnlinePaymentExpired:vn.uit.edu.msshop.order.domain.event.OnlinePaymentExpired,
                    OnlinePaymentCancelled:vn.uit.edu.msshop.order.domain.event.OnlinePaymentCancelled,
                    CodPaymentCreated:vn.uit.edu.msshop.order.domain.event.CodPaymentCreated,
                    ForceCancellOrder:vn.uit.edu.msshop.order.domain.event.inventory.ForceCancellOrder,
                    ProductCreated:vn.uit.edu.msshop.order.domain.event.product.ProductCreated,
                    ProductUpdated:vn.uit.edu.msshop.order.domain.event.product.ProductUpdate,
                    VariantUpdated:vn.uit.edu.msshop.order.domain.event.product.VariantUpdate,
                    VariantDeleted:vn.uit.edu.msshop.order.domain.event.product.VariantDeleted,
                    ProductDeleted:vn.uit.edu.msshop.order.domain.event.product.ProductDeleted,
                    PaymentSuccess:vn.uit.edu.msshop.order.domain.event.PaymentSuccess
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                max.block.ms: 3000
                delivery.timeout.ms: 5000
                request.timeout.ms: 2000
                spring.json.type.mapping: 
                    OrderCreated:vn.uit.edu.msshop.order.domain.event.OrderCreated,
                    OnlinePaymentCancelled:vn.uit.edu.msshop.order.domain.event.OnlinePaymentCancelled,
                    CodPaymentCancelled:vn.uit.edu.msshop.order.domain.event.CodPaymentCancelled,
                    CodPaymentReceived:vn.uit.edu.msshop.order.domain.event.CodPaymentReceived,
                    OrderCreatedSuccess:vn.uit.edu.msshop.order.domain.event.OrderCreatedSuccess,
                    OrderCreated_Inventory:vn.uit.edu.msshop.order.domain.event.inventory.OrderCreated,
                    OrderCancelled:vn.uit.edu.msshop.order.domain.event.inventory.OrderCancelled,
                    OrderShipped:vn.uit.edu.msshop.order.domain.event.inventory.OrderShipped,
                    IncreaseSoldCountEvents:vn.uit.edu.msshop.order.domain.event.IncreaseSoldCountEvents
logging:
  level:
        org.springframework.data.mongodb.core.MongoTemplate: OFF
        org.apache.kafka: ERROR
        org.springframework.kafka: ERROR
        io.micrometer.tracing: ERROR
        io.zipkin.reporter2: ERROR
        root: WARN
        vn.uit.edu.msshop.order: INFO
        io.lettuce.core: WARN
  pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
        endpoints:
            web:
        exposure:
            include: "*"
        tracing:
            sampling:
                probability: 1.0 
        zipkin:
            tracing:
                endpoint: http://127.0.0.1:9411/api/v2/spans
        metrics:
            tags:
                application: ${spring.application.name}
server:
  port: 8000
  address: 0.0.0.0

    
    

    