server:
    port: 8074

spring:
    mongodb:
        uri: mongodb://alibou:alibou@localhost:27023/order_db?authSource=admin&uuidRepresentation=STANDARD&maxPoolSize=200&minPoolSize=20
    command-listener:
        observation:
            enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5435/payment
        username: alibou
        password: alibou
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        show-sql: true
        properties:
            hibernate:
                "[globally_quoted_identifiers]": true
                "[globally_quoted_identifiers_skip_column_definitions]": true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 6MB
    kafka:
        bootstrap-servers: localhost:9092 
        consumer:
            group-id: account-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
                spring.json.type.mapping: 
                    OrderCreated:vn.uit.edu.payment.domain.event.OrderCreated,
                    CodPaymentCancelled:vn.uit.edu.payment.domain.event.CodPaymentCancelled,
                    CodPaymentReceived:vn.uit.edu.payment.domain.event.CodPaymentReceived,
                    OnlinePaymentCancelled:vn.uit.edu.payment.domain.event.OnlinePaymentCancelled
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: 
                    OnlinePaymentExpired:vn.uit.edu.payment.domain.event.OnlinePaymentExpired,
                    OnlinePaymentCancelled:vn.uit.edu.payment.domain.event.OnlinePaymentCancelled,
                    CodPaymentCreated:vn.uit.edu.payment.domain.event.CodPaymentCreated,
                    PaymentSuccess:vn.uit.edu.payment.domain.event.PaymentSuccess
logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
payos:
    client-id: 12c6330d-6619-407c-ab25-6a2e7eaf8f0a
    api-key: 3d007e3b-9f27-46e4-b469-6be53e180181
    checksum-key: e989cd5d9989a981d49da94f9d9a363f5886ba4568edca3a52fc1cc1b51b7699