server:
    port: 8074

spring:
    
    command-listener:
        observation:
            enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${PAYMENT_DB_URL:localhost:5435}/payment
        username: alibou
        password: alibou
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        show-sql: false
        properties:
            hibernate:
                "[globally_quoted_identifiers]": true
                "[globally_quoted_identifiers_skip_column_definitions]": true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 6MB
    kafka:
        bootstrap-servers: ${KAFKA_URL:localhost:9092} 
        consumer:
            group-id: account-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
                spring.json.type.mapping: 
                    OrderCreated:vn.uit.edu.payment.domain.event.OrderCreated,
                    CodPaymentCancelled:vn.uit.edu.payment.domain.event.CodPaymentCancelled,
                    CodPaymentReceived:vn.uit.edu.payment.domain.event.CodPaymentReceived,
                    OnlinePaymentCancelled:vn.uit.edu.payment.domain.event.OnlinePaymentCancelled,
                    OrderUpdatedEvent:vn.uit.edu.payment.domain.event.OrderUpdatedEvent
        producer:
            bootstrap-servers: ${KAFKA_URL:localhost:9092}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: 
                    OnlinePaymentExpired:vn.uit.edu.payment.domain.event.OnlinePaymentExpired,
                    OnlinePaymentCancelled:vn.uit.edu.payment.domain.event.OnlinePaymentCancelled,
                    CodPaymentCreated:vn.uit.edu.payment.domain.event.CodPaymentCreated,
                    PaymentSuccess:vn.uit.edu.payment.domain.event.PaymentSuccess,
                    PaymentLinkCreated:vn.uit.edu.payment.domain.event.PaymentLinkCreated,
                    OnlinePaymentSuccess:vn.uit.edu.payment.domain.event.OnlinePaymentSuccess,
                    PaymentCreatedFail:vn.uit.edu.payment.domain.event.PaymentCreatedFail
logging:
  level:
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR
payos:
    client-id: 
    api-key: 
    checksum-key: 
eureka:
    client:
        serviceUrl:
            defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5 
        lease-expiration-duration-in-seconds: 10