server:
    port: 8070

spring:
    output:
        ansi:
            enabled: ALWAYS
    mongodb:
        host: localhost
        port: 27017
        database: product
        username: alibou
        password: alibou
        authentication-database: admin
        representation:
            uuid: STANDARD 
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 6MB
    kafka:
        bootstrap-servers: localhost:9092 
        consumer:
            group-id: product-service-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                "[spring.json.trusted.packages]": "*"
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping:
                    VariantUpdatedIntegrationEvent:vn.edu.uit.msshop.product.variant.application.dto.integration.VariantUpdatedIntegrationEvent,
                    VariantSoftDeletedIntegrationEvent:vn.edu.uit.msshop.product.variant.application.dto.integration.VariantSoftDeletedIntegrationEvent,
                    ProductCreated:vn.edu.uit.msshop.product.shared.event.domain.ProductCreated,
                    ProductUpdated:vn.edu.uit.msshop.product.shared.event.domain.ProductUpdate,
                    VariantUpdate:vn.edu.uit.msshop.product.shared.event.domain.VariantUpdate,
                    VariantDeleted:vn.edu.uit.msshop.product.shared.event.domain.VariantDeleted,
                    ProductDeleted:vn.edu.uit.msshop.product.shared.event.domain.ProductDeleted,
                    VariantRestore:vn.edu.uit.msshop.product.shared.event.domain.VariantRestore,
                    VariantPurge:vn.edu.uit.msshop.product.shared.event.domain.VariantPurge

    cloud:
        openfeign:
            client:
                config:
                    order-service:
                        connect-timeout: 3000
                        read-timeout: 10000
    task:
        scheduling:
            pool:
                size: 1

logging:
    level:
        "[vn.edu.uit.msshop]": DEBUG
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG