server:
    port: 8070

spring:
    output:
        ansi:
            enabled: ALWAYS
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 6MB
    mongodb:
        host: ${PRODUCT_DB_HOST:localhost}
        port: ${PRODUCT_DB_PORT:27017}
        database: product
        username: alibou
        password: alibou
        authentication-database: admin
        representation:
            uuid: STANDARD 
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            timeout: 200ms
            connect-timeout: 500ms
            repositories:
                enabled: false
    cache:
        type: redis
        redis:
            cache-null-values: false
    kafka:
        bootstrap-servers: ${KAFKA_URL:localhost:9092}
        consumer:
            group-id: product-service-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                "[spring.json.trusted.packages]": "*"
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                "[spring.json.type.mapping]": >
                    VariantUpdatedIntegrationEvent:vn.edu.uit.msshop.product.variant.application.dto.integration.VariantUpdatedIntegrationEvent,
                    VariantSoftDeletedIntegrationEvent:vn.edu.uit.msshop.product.variant.application.dto.integration.VariantSoftDeletedIntegrationEvent
    cloud:
        openfeign:
            client:
                config:
                    order-service:
                        connect-timeout: 3000
                        read-timeout: 10000
    task:
        scheduling:
            pool:
                size: 1

app:
    cache:
        key-prefix: ${spring.application.name}
        brand-ttl: 1h
        brand-list-ttl: 30m
        category-ttl: 1h
        category-list-ttl: 30m
        product-ttl: 1h
        product-list-ttl: 5m
        variant-ttl: 1h
        variant-list-ttl: 5m
        circuit-breaker:
            sliding-window-size: 10
            minimum-number-of-calls: 5
            failure-rate-threshold: 50
            wait-duration-in-open-state: 5s
            permitted-number-of-calls-in-half-open-state: 3

logging:
    level:
        "[vn.edu.uit.msshop]": INFO
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: WARN
eureka:
    client:
        serviceUrl:
            defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5 
        lease-expiration-duration-in-seconds: 10