server:
    port: 8070

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/order
        username: alibou
        password: alibou
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        show-sql: true
        properties:
            hibernate:
                "[globally_quoted_identifiers]": true
                "[globally_quoted_identifiers_skip_column_definitions]": true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 6MB