spring:
    application:
        name: product-service
    config:
        import: optional:configserver:http://localhost:8888
    cloud:
        config:
            fail-fast: true
            retry:
                max-attempts: 5

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
                