# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Chỉ copy đúng pom.xml và source code của account-service
COPY backend/services/auth-service/auth/pom.xml backend/services/auth-service/auth/
RUN mvn -f backend/services/auth-service/auth/pom.xml dependency:go-offline -B

COPY backend/services/auth-service/auth/src backend/services/auth-service/auth/src
RUN mvn clean package -f backend/services/auth-service/auth/pom.xml -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/backend/services/auth-service/auth/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]