server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations
management:
    tracing:
        sampling:
            probability: 0.1 # Giảm từ 100% xuống 10% để giảm disk I/O
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans