server:
    port: 8888

spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations
management:
    tracing:
        sampling:
            probability: 1.0 # Gửi toàn bộ 100% request để dễ debug
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans