spring:
    application:
        name: api-gateway
    config:
        import: optional:configserver:http://localhost:8888
    cloud:
        config:
            fail-fast: true
            retry:
                max-attempts: 5
        gateway:
            server:
                webflux:
                    discovery:
                        locator:
                            enabled: true
                    routes:
                      - id: payment-service
                        uri: lb:http://PAYMENT-SERVICE
                        predicates:
                        - Path=/payment/**
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      enabled: true
